### ISSUE TITLE
Support history 4.0.0

### ISSUE THREAD

**Issue by petyappetrov** [taion/scroll-behavior#101]
```
Module not found: Error: Cannot resolve module 'history/lib/Actions
Module not found: Error: Cannot resolve module 'history/lib/DOMStateStorage
```

**Comment by taion** [comment]
I do not intend on addressing this. Also, history enhancers no longer exist.

**Comment by barbalex** [comment]
I began a project using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) and now I get this error when running `npm i` too. I'm sure plenty of other people are affected too.

Sorry for bugging but I don't get why this should not be addressed: Is there a simple way to sidestep this problem?

Would it be a good idea to remain on the last working version of history, as it seems that it does not occur in older versions of history?

**Comment by barbalex** [comment]
Also: What do you mean with:

> Also, history enhancers no longer exist

After all, the official react-router docs still use it: https://github.com/ReactTraining/react-router#whats-it-look-like

**Comment by barbalex** [comment]
I think I got it: Seems like `history` was in react-boilerplate's package.json until recently but was referenced nowhere. In fact removing it solves this issue for me.

**Comment by taion** [comment]
There is no way to "sidestep" this problem. For the time being, if you want to use this library, use history v2.

**Comment by barbalex** [comment]
thanks
