### ISSUE TITLE
History lib should be updated

### ISSUE THREAD

**Issue by justinr1234** [taion/scroll-behavior#104]
The directory structure of history has completely changed so that all the imports in this repo are failing:  https://github.com/taion/scroll-behavior/blob/4e56d93e018d3d1d345d92ef0ebf465e11a53815/src/ScrollBehavior.js#L9

**Comment by taion** [comment]
There is an explicitly marked peer dependency for the specific version of history: https://github.com/taion/scroll-behavior/blob/v0.8.2/package.json#L42

The only way the imports here could be "failing" is if you're ignoring the npm errors from incompatible package installed.

**Comment by justinr1234** [comment]
I realize that, but why not update to support the newer lib?

**Comment by taion** [comment]
history v4 removed the concept of "history middlewares", so this library makes no sense in context there.

**Comment by justinr1234** [comment]
Ah ok, thanks for the info
