### ISSUE TITLE
Using scroll-behavior with react-custom-scrollbars

### ISSUE THREAD

**Issue by Zephir77167** [taion/scroll-behavior#105]
Hello,

I've implemented the code in the documentation to apply scroll behavior on my router, but I'm using react-custom-scrollbars (https://github.com/malte-wessel/react-custom-scrollbars), therefore nothing happens...

Is there a way I could call window.scrollbar.scrollToTop() (my way of scrolling to the top with my custom scrollbar) when useScroll normally scrolls?

Thanks in advance.

**Comment by taion** [comment]
Like I said, I'd be willing to consider a PR to add this sort of feature.
