### ISSUE TITLE
Doesn't work with latest history package.

### ISSUE THREAD

**Issue by AlastairTaft** [taion/scroll-behavior#106]
The docs recommend doing

```
import createHistory from 'history/lib/createBrowserHistory'
```
whereas the history package says
```
import createHistory from 'history/createBrowserHistory'
```

Also when I make the adjustments to drop the 'lib' it throws up on some internal code because of the lib pathname.

```
Uncaught Error: Cannot find module "history/lib/Actions"
```

**Comment by taion** [comment]
https://github.com/taion/scroll-behavior/blob/master/package.json#L42

See also earlier closed issues

**Comment by AlastairTaft** [comment]
Thanks will use v2 of the history package.
