### ISSUE TITLE
Scroll is being reset on `push`

### ISSUE THREAD

**Issue by halt-hammerzeit** [taion/scroll-behavior#113]
```js
  _getScrollTarget(key, shouldUpdateScroll, prevContext, context) {
    const location = this._getCurrentLocation();
    if (location.action === 'PUSH') {
      return [0, 0];
    }
```

Suppose a user is searching for a query, and a new location (`?query=...`) is pushed.
That would reset scroll position while it should have not.

**Comment by taion** [comment]
Try doing

```js
window.location.href = '?foo'
```

on a normal web page.

As always, we provide hooks to control the details of what you want.

**Comment by halt-hammerzeit** [comment]
No, this won't do because the page is reloaded and the target behaviour is the opposite.

I found my solution though - `shouldUpdateScroll`.

**Comment by taion** [comment]
I am saying that the default scroll behavior here matches exactly what you would get if you were doing normal page navigation.

**Comment by halt-hammerzeit** [comment]
Ok
