### ISSUE TITLE
Cannot set property scrollRestoration of [object History] which has only a getter

### ISSUE THREAD

**Issue by vizath** [taion/scroll-behavior#126]
I get this error within Bugsnag, all coming from `66.249.88.*`, or `66.102.6.*`, which seems to be Google (google-proxy-66-249-88-154.google.com (https://mxtoolbox.com/SuperTool.aspx?action=ptr%3a%09+66.249.88.152)).

It seems to be a robot that would execute JS on pages, using a real browser user-agent (`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36`). Could be the Google pre-fetch?

Anyways, the issue is more about the noise than an issue for us since our app is behind a login, but I don't know what could be the side effect of that error for public websites.

Add a try catch in there ?

https://github.com/taion/scroll-behavior/blob/493c9b07a9cff42d01489aed0264f49fd56b61ef/src/index.js#L27-L32

**Comment by taion** [comment]
Sounds good. Want to PR it?
