### ISSUE TITLE
Use passive event listeners

### ISSUE THREAD

**Issue by alexandernanberg** [taion/scroll-behavior#131]
Use passive event listeners to improve perf

https://developers.google.com/web/updates/2016/06/passive-event-listeners

**Comment by taion** [comment]
![image](https://user-images.githubusercontent.com/3112159/49091437-df621f80-f22d-11e8-903f-66fa8bed37c2.png)

**Comment by alexandernanberg** [comment]
I wonder if that applies to this tho. I get Lighthouse warning about this, but they could be false positives 🤔
