### ISSUE TITLE
scroll position not saved on PUSH

### ISSUE THREAD

**Issue by KyleAMathews** [taion/scroll-behavior#135]
![kapture 2019-03-02 at 9 57 30](https://user-images.githubusercontent.com/71047/53685711-24856a00-3cd3-11e9-9b6f-e6ee2d2c516d.gif)

If I scroll just a little bit at the top it'll then record the new scroll position.

What's the right solution here? Does Gatsby need to manually handle this? I added `this.scrollBehavior._saveWindowPosition()` to https://github.com/gatsbyjs/gatsby/blob/888c124d24aea36a57086d096154ecacf44f0980/packages/gatsby-react-router-scroll/src/ScrollBehaviorContext.js#L58 — which fixes the immediate problem but I'm not 100% sure there are not other implications from doing this.

**Comment by taion** [comment]
Okay, so, to make sure I understand. The pattern is:

1. PUSH to `/a`
2. Scroll to `y1`
3. PUSH to `/b`
4. PUSH to `/a`
5. Scroll to `y2`
6. POP to `/b`
7. POP to `/a` -> scroll is restored to `y2`, not `y1`

What's happening here is that this library was written with the idea of using the `location.key` provided by older versions of history to index unique scroll locations: https://github.com/taion/react-router-scroll/blob/94dae388b88c7366e7712847e2fcb99f7b858f08/src/StateStorage.js#L18-L22

(and in fact I do something similar with Found). The issue in Gatsby is that the key looks to be derived purely from the path: https://github.com/gatsbyjs/gatsby/blob/888c124d24aea36a57086d096154ecacf44f0980/packages/gatsby-react-router-scroll/src/StateStorage.js#L49

which explains the behavior above

**Comment by KyleAMathews** [comment]
That explains it! We can fix this, thanks!
