### ISSUE TITLE
Route specific scroll configuration

### ISSUE THREAD

**Issue by florrain** [taion/scroll-behavior#17]
Hi,

Because the `history` prop is passed to the React `Router` and not to a `Route`, I'm assuming this is not possible to have this route use simpleScroll (ex: shop listing view) and that route use scrollToTop (ex: product detail view).

Would you have any recommendations to accomplish that?

Thanks.

**Comment by taion** [comment]
Right now? No - that possibility is precluded by the current API.

That doesn't mean we won't support it - it just means we have to change the API.

**Comment by florrain** [comment]
Okay wanted to make sure. 

Well I will be very interested if it ends up in a future release : ).

Closing this issue.

**Comment by taion** [comment]
Let's leave this open for now - there are broader issues related to the current API, and this issue is as good as any.

**Comment by tomconroy** [comment]
Hi, is there a workaround to get this working for now?

**Comment by taion** [comment]
Not really. The current implementation doesn't know about routes at all. Maybe it'd have to be some event-emitter-y thing but you'd have to write a fair bit of code.

**Comment by florrain** [comment]
Correct me @taion if I'm wrong.

You can register event listeners on your own app's history object. This is what this repo actually does, each scroll rule in the readme has a different listen handler. You can still do the same yourself and add specific patches depending on your needs while there's no better solution.

Here's a snippet:
```javascript
const history = createBrowserHistory();

history.listenBefore(function() {
  // Here you have the window.location before the route changes. You can save it into a global var, the scroll position shouldn't be changed at that point (assumption). It's called before history.listen.
});

// Nothing fancy here, it's what useSimpleScroll does.
history.listen(function(newLocation) {
  // Don't scroll if it's a pop event (ex: browser back button)
  if (newLocation.action === 'POP') {
    return;
  }

  // Otherwise, scroll to the top after a few milliseconds.
  setTimeout(() => { window.scrollTo(0, 0); });
});
```

You can also save the scroll position in your application before you change routes, put it into a store (flux store, session storage, ...) and restore it when you come back to the same route. Still not the best or cleanest solution but that can work.

**Comment by taion** [comment]
I was thinking of emitting an event from the scroll behavior and letting subscribers call `preventDefault` or something on it.

**Comment by tomconroy** [comment]
Thanks @florrain, very helpful!

**Comment by jackyon** [comment]
hm... looks like the scroll behavior still have some issues?

for example, I test this on the mobile safari, when I click back button, the position scroll to the top, it can't remember the last scroll position.

any solution for this?

plz advise, thx.

**Comment by taion** [comment]
For now, use `shouldUpdateScroll` to customize scroll behavior.
