### ISSUE TITLE
Option to ignore query?

### ISSUE THREAD

**Issue by isTravis** [taion/scroll-behavior#20]
Great work with scroll-behavior - it's saved me in some pretty tricky jams! Thank you!

I'm wondering if there's any way to have scroll-behavior ignore changes to the query parameters of the url. I have a search field that updates the ?search=  query parameter. I don't want my page to scroll to the top on every update of this.

Any ideas?

Thanks again.

**Comment by taion** [comment]
I'd like to have a general way to suppress the scroll behavior, but I don't have anything yet - I need to adjust the API first due to planned upstream router changes.

**Comment by dylanscott** [comment]
Is this something you're still waiting on larger API changes to consider? It seems like a common pattern (e.g. with `history/lib/useBasename` and `history/lib/useQueries`) to enable additional options on the resulting `createHistory` function. I could imagine one here that would enable conditionally suppressing scroll behavior based on a callback. I'm happy to create a PR for this, even if just to brainstorm what the API could look like.

**Comment by taion** [comment]
Fixed by #35.
