### ISSUE TITLE
Scroll to hash anchor

### ISSUE THREAD

**Issue by blindsteal** [taion/scroll-behavior#22]
What is the preferred way to implement a hash/anchor-link scrolling behavior as in https://github.com/rackt/react-router/issues/2144#issuecomment-153899046 ? So far I found 2 solutions:
1. continue using history.listen (although using setTimeout in order to wait for the router behavior to evaluate seems pretty unreliable)
2. create a useHashScroll decorator function using the /utils of this repo

**Comment by taion** [comment]
It should be part of the "standard" scroll behavior here IMO.

**Comment by taion** [comment]
Known missing feature.

**Comment by bySabi** [comment]
@ihinsdale @taion 
Why this commit is not already merge? Cause `scrollIntoView` browser compatibility?

**Comment by taion** [comment]
What commit are you talking about?

**Comment by bySabi** [comment]
@ihinsdale commit: https://github.com/ihinsdale/scroll-behavior/commit/0f54595b3e66d270d077c2cf6b3fb95688679e5f

sorry!  I don´t see is 21 hours old :-)

could be valid for `anchor` hash scrolling?

**Comment by SpainTrain** [comment]
Created a PR based on solution 1 to keep the discussion going. #47

**Comment by StevenLangbroek** [comment]
I got this working by using the following `shouldUpdateScroll`, along with `Velocity` for smooth scrolling:

```js
import Velocity from 'velocity-animate';

const SCROLL_TRANSITION = {
  duration: 500,
  easing: 'ease-in-out'
};

const scrollToTop = () => {
  if (window.scrollY === 0) return false;
  Velocity.animate(document.body, 'scroll', SCROLL_TRANSITION);
  return false;
};

const scrollToEl = (el) => {
  Velocity.animate(el, 'scroll', SCROLL_TRANSITION);
  return false;
};

export default (oldLocation, newLocation) => {
  if (oldLocation &&
    (oldLocation.pathname + oldLocation.hash === newLocation.pathname + newLocation.hash)
  ) {
    return scrollToTop();
  }
  if (newLocation.hash) {
    const targetEl = document.querySelector(newLocation.hash);
    if (!targetEl) return false;
    return scrollToEl(targetEl);
  }
  return scrollToTop();
};
```

**Comment by taion** [comment]
That works. I don't plan on integrating with Velocity here, but I do want to handle the "base" case of scrolling to hash anchors.

**Comment by StevenLangbroek** [comment]
Thought so, but it's easy enough to remove right?

**Comment by taion** [comment]
Hopefully.

**Comment by StevenLangbroek** [comment]
Just noticed this fails when you switch to another route with a hash. The `targetEl` isn't available yet, so it bails with `return false;`. I added a retry function for my own code, but do you think there's a more elegant solution maybe?

Retry:

```js
const retry = (hash) => setTimeout(
  () => {
    const targetEl = document.querySelector(hash);
    return targetEl ? scrollToEl(targetEl) : null;
  },
  200
);
```

**Comment by taion** [comment]
I'm not sure. With the router, it's supposed to be the case that those changes have already been flushed to the DOM. Try forcing a reflow, maybe? Otherwise I can't think of anything better than what you have.

**Comment by StevenLangbroek** [comment]
You mean on the element or on some container?

**Comment by taion** [comment]
Before trying to grab the element.

**Comment by StevenLangbroek** [comment]
No dice. I'll stick to the `retry` approach for now. Cheers!

**Comment by 0x80** [comment]
I think requestAnimationFrame is more appropriate then a timeout of 200ms. In my app the target element seems to be found on the next frame, but I kept a retry just in case.

```javascript

function shouldUpdateScroll (oldLocation, newLocation) {
  if (newLocation.hash && newLocation.action !== 'POP') {
    window.requestAnimationFrame(() => scrollToHash(newLocation.hash))
    return false
  } else {
    return pageChanged(oldLocation, newLocation)
  }
}

function scrollToHash(hash) {
  const el = document.querySelector(hash)
  if (!el) {
    retry(() => scrollToHash(hash))
  } else {
    const { top } = el.getBoundingClientRect()
    window.scrollTo(0, window.pageYOffset + top)
  }
}

const retry = (fn) => window.requestAnimationFrame(fn)

function pageChanged(oldLocation, newLocation) {
  return (oldLocation && oldLocation.pathname) !== newLocation.pathname
}
```

**Comment by kjs3** [comment]
I think an issue I posted to React is relevant here. https://github.com/facebook/react/issues/7889

**Comment by SpainTrain** [comment]
@kjs3 thanks for linking to the React issue :+1:. That is a good thing to be aware of.

@0x80 you are completely correct!  I have switched to using https://github.com/taion/react-router-scroll and this is my middleware:

```js
const scrollRouterMiddleware = useScroll((prevRouterProps, {routes, location}) => {
    if (some(routes, 'ignoreScrollBehavior')) {
        return false
    }

    if (some(routes, 'scrollToTop')) {
        return [0, 0]
    }

    if (conformsTo(location, {hash: negate(isEmpty), action: (a) => a !== 'POP'})) {
        invoke(window, 'requestAnimationFrame', () => {
            const node = document.getElementById(location.hash.substr(1))
            if (node) {
                node.scrollIntoView()
            }
        })
    }

    return true
})
```

(N.B. `some`, `invoke`, `conformsTo`, `negate` are lodash functions)

**Comment by ihinsdale** [comment]
@aij @taion Thanks for this!
