### ISSUE TITLE
Usage with react-router?

### ISSUE THREAD

**Issue by jonathanong** [taion/scroll-behavior#39]
it includes history now and there's no `createBrowserHistory()` function, so i'm not sure how to use this anymore

**Comment by taion** [comment]
You'll have to follow this pattern until I get a chance to rewrite the lib: https://github.com/reactjs/react-router/blob/095ed6cf51d3c4755f13b428182e8ec2df593277/upgrade-guides/v2.0.0.md#using-custom-histories
