### ISSUE TITLE
shouldUpdateScroll and bug with updating currentKey inside updateScroll in useStandardScroll and others

### ISSUE THREAD

**Issue by northerneyes** [taion/scroll-behavior#40]
`shouldUpdateScroll` is great, but it has one small issue. When you don't call method `updateScroll` in `useStandardScroll.js`, for example, you also don't update `currentKey` in here, and it starts to track wrong page from this moment.
So we need always to update `currentKey` for `useStandardScroll`, but not invoke `window.scrollTo`.

**Comment by taion** [comment]
PRs welcome.

**Comment by Aweary** [comment]
My first thought is that the easiest way to do this without changing the internal API too much would be to pass `shouldUpdate` as a second argument to `updateScroll` with a default of `true` that returns after setting `currentKey = key` if it's `false`

**Comment by northerneyes** [comment]
I've fixed this bug already in my fork (these changes https://github.com/northerneyes/scroll-behavior/commit/c582bf57f9e6295dd9e37b9e4a455b9b78b714bb), but I'm too lazy to create a PR)

**Comment by Aweary** [comment]
That's the spirit!
