### ISSUE TITLE
Use passive listeners when listening for scroll events

### ISSUE THREAD

**Issue by satazor** [taion/scroll-behavior#405]
Using `{ passive: true )` should improve the performance of scroll listeners, see https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners.

**Comment by taion** [comment]
The exact docs you linked at the bottom explicitly say:
![image](https://user-images.githubusercontent.com/3112159/91113552-e3fe7680-e653-11ea-864c-919212e10b4c.png)

**Comment by satazor** [comment]
Sorry, haven't read that part!
