### ISSUE TITLE
scrolls to top in async action 

### ISSUE THREAD

**Issue by AnuragSinghTomarr** [taion/scroll-behavior#42]
The scenario is that suppose i am on url localhost:3030/home than i scroll to the middle of mine page and I click a link localhost:3030/about as i click on this link i am doing some Api call after the call is complete i go to about page. But as i click on the  link mine page scrolls to top than after the i get dta from API i am being routed to about page. So how can i stop going to top of the page.
Any help will be useful.

**Comment by taion** [comment]
There won't be support for async router transitions until the rewrite. Any other async handling is out of scope here.
