### ISSUE TITLE
onChange not firing on history back on chrome in iOS

### ISSUE THREAD

**Issue by viktorkalajo** [taion/scroll-behavior#45]
Im using scroll-behavior (useStandardScroll) together with react-router 2.0. I'm having an issue on chrome in iOS: it seems that the [`onChange` method in createUseScroll.js](https://github.com/taion/scroll-behavior/blob/master/modules/utils/createUseScroll.js#L42) is not firing when i move back and forth in history and hence doesnt `updateScroll` fire, leaving me on the top of the page instead of on the correct scroll-position. It fires whenever i click a link and it works fine in other browsers such as safari on iOS.

Has anyone experienced similar issues or have an idea for a fix?

**Comment by taion** [comment]
`onChange` just fires when the history fires. If the history isn't firing, that sounds like a bug upstream somewhere. Are you using this with React Router?

**Comment by taion** [comment]
@viktorkalajo This is possibly a lifecycle thing. Most likely fixed if you use react-router-scroll.
