### ISSUE TITLE
Scroll position incorrect on back button press

### ISSUE THREAD

**Issue by TheSisb** [taion/scroll-behavior#50]
I'm using `useSimpleScroll` with 
```
shouldUpdateScroll: (oldLocation, newLocation) => {
    return oldLocation ? newLocation.action !== "POP" : false;
}
```

If I'm on a short page (height 1000px) and navigate back to a longer page (height 5000px) then it will scroll down that page to max 1000px, even though I intend to reach position 3500px for example.

Is there a way to fix this so scroll-behavior scrolls all the way down correctly? Perhaps a setTimeout somewhere?

**Comment by taion** [comment]
`useSimpleScroll` doesn't do anything on `POP` anyway: https://github.com/taion/scroll-behavior/blob/master/modules/useSimpleScroll.js#L20-L26

If this is on Firefox with hash history, then this isn't really fixable without `useStandardScroll`.

**Comment by TheSisb** [comment]
Well when I use `useStandardScroll` and hit the back button, the previous page is being scrolled to the position I just left, not the actual position it should have retained. :/

**Comment by taion** [comment]
Are you using async routes?

**Comment by TheSisb** [comment]
I don't believe so.  0 ajax, pure react+react-router site.

**Comment by taion** [comment]
Are you doing an AJAX load to populate the previous page?

**Comment by TheSisb** [comment]
No, I am not

**Comment by taion** [comment]
Which history and browser are you using?

**Comment by TheSisb** [comment]
```
import createBrowserHistory from 'history/lib/createBrowserHistory';
import useRouterHistory from 'react-router/lib/useRouterHistory';
import useScroll from 'scroll-behavior/lib/useStandardScroll';

let history = useRouterHistory(useScroll(createBrowserHistory))({
    queryKey: false,
    shouldUpdateScroll: (oldLocation, newLocation) => {
      return oldLocation ? newLocation.action !== "POP" : false;
    }
  });
```

Chrome latest stable.  React-router 2, React 14

**Comment by taion** [comment]
`useStandardScroll` requires having a query key when using hash history, as we use the state to remember the scroll position.

In `useSimpleScroll`, we let the browser take care of scroll restoration on `POP` actions anyway, so there's nothing relevant in this library.

**Comment by TheSisb** [comment]
Got it, thanks.
