### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pathname' of null

### ISSUE THREAD

**Issue by gudh** [taion/scroll-behavior#67]
Hi, thanks for building the component!

I first came across your [solution here](https://github.com/reactjs/react-router/issues/2019#issuecomment-204764984), and it works well for me, back when it's version 0.4.0.

Today, I saw your 0.6.0 update, so I upgrade to it, and update the code.

according to the [docs](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#using-scroll-behavior) I changed from (0.4.0 code, which works)
```javascript
const hashHistory = useScroll(useRouterHistory(createHashHistory))();
```

to 

```javascript
const hashHistory = withScroll(useRouterHistory(createHashHistory)());
```

which work as well, however if I use add the code in the README, like so 

```javascript
const hashHistory = withScroll(useRouterHistory(createHashHistory)(), (prevLocation, location) => (
  // Don't scroll if the pathname is the same.
  location.pathname === prevLocation.pathname ? [0, 0] : true
));
```

I got `Uncaught TypeError: Cannot read property 'pathname' of null`

prevLocation is null? 

Let me know if I am wrong, thanks!

**Comment by taion** [comment]
That's a docs bug. `prevLocation` is `null` on the initial page load.
