### ISSUE TITLE
Don't put scrollPosition on location.state

### ISSUE THREAD

**Issue by taion** [taion/scroll-behavior#69]
Putting scrollPosition on `location.state` is not ideal, as it leads to odd things happening if the user does something like `history.push({ ...location, query: { the: 'query' } })`.

We should probably use a different key space from history for tracking scroll position. Need to look into and understand use cases that are currently looking at `location.state.scrollPosition` though.

cc @jondkoon

**Comment by jondkoon** [comment]
All I need is the ability to get the previous locations scroll position when shouldUpdateScroll is called, so I can store it and reference it later. We could ask the dom, but it seems a bit wasteful since scroll-behavior already does that.

**Comment by taion** [comment]
I'll probably handle this by making `scrollPosition` a top-level key in the state object in react-router-scroll or something.

**Comment by taion** [comment]
I just realized that I have no idea why it's even possible to read `prevLocation.state.scrollPosition`. That usually shouldn't even be there, unless I'm badly misunderstanding something.

**Comment by jondkoon** [comment]
Looks something like this in my code. Definitely would prefer a more straight forward way to get it.

```js
import { readState } from 'history/lib/DOMStateStorage';
...
const previousScrollPosition = (oldLocation && readState(oldLocation.key) || {}).scrollPosition;
...
```

**Comment by taion** [comment]
The API will probably be something along the lines of `this.getScrollPosition(prevLocation)` from the callback, BTW.

**Comment by jondkoon** [comment]
Cool. Sounds great!

**Comment by taion** [comment]
See tests added in #73. I'm intentionally leaving this out of the docs because this API is a bit gross, but I can't really think of a cleaner way to expose this functionality – I explicitly don't want to add this to `location`, because I don't want people doing `history.push({ ...location, query: newQuery })` to hit this.

**Comment by taion** [comment]
And with react-router-scroll: https://github.com/taion/react-router-scroll/blob/master/test/useScroll.spec.js#L87-L91

**Comment by jondkoon** [comment]
Perfect. Thanks @taion  - My team is revisiting our InfiniteList component which may change how we handle scroll management. My plan is to integrate react-router-scroll after that settles if it is still applicable. I'll let you know how it goes.
