### ISSUE TITLE
Can't get the latest version to work.

### ISSUE THREAD

**Issue by nikhildaga** [taion/scroll-behavior#70]
0.6 version of scroll-behavior with react-router 2.4 and history 2.1 

Using this code, gives 
Module not found: Error: Cannot resolve module 'scroll-behavior/lib/useScrollToTop'

```
import { createHistory } from 'history'
import { applyRouterMiddleware, Router, useRouterHistory } from 'react-router';
import useScroll from 'scroll-behavior/lib/useScrollToTop'

const history = useRouterHistory(useScroll(createHistory))()
```

The following code gives warning,

Warning: [react-router] It appears you have provided a deprecated history object to `<Router/>`, please use a history provided by React Router with `import { browserHistory } from 'react-router'` or `import { hashHistory } from 'react-router'`. If you are using a custom history please create it with `useRouterHistory`, see http://tiny.cc/router-usinghistory for details.
```
import createHistory from 'history/lib/createBrowserHistory';
import withScroll from 'scroll-behavior';

const history = withScroll(createHistory());

```

**Comment by taion** [comment]
See the docs. The API has changed in recent versions.

**Comment by nikhildaga** [comment]
The code given in docs https://github.com/taion/scroll-behavior#usage leads to warning: 

Warning: [react-router] It appears you have provided a deprecated history object to <Router/>, please use a history provided by React Router with import { browserHistory } from 'react-router' or import { hashHistory } from 'react-router'. If you are using a custom history please create it with useRouterHistory, see http://tiny.cc/router-usinghistory for details.
