### ISSUE TITLE
Can we scroll some other element instead of Window?

### ISSUE THREAD

**Issue by Brendan-csel** [taion/scroll-behavior#75]
Sorry if I've missed this somewhere. Our page layout has a fixed sidebar and content section. The content element contains the page content and this is the element that scrolls.

Can I define the scroll container element to be something other than "window"?

**Comment by taion** [comment]
Not yet.

**Comment by jamielob** [comment]
@taion - would you accept a PR for this? It looks like it would just be a case of passing in an optional container ID and the passing that to the scroll functions in place of the window reference.

**Comment by taion** [comment]
That's not quite what I'm looking for here – ideally additional scrollable containers should be able to "register" themselves, such that we can manage scroll location for multiple containers at the same time.

**Comment by Mesoptier** [comment]
Have a look at this PR: https://github.com/taion/scroll-behavior/pull/86

**Comment by taion** [comment]
Closed in #86.

**Comment by taion** [comment]
Released in v0.8.0.
