### ISSUE TITLE
Purpose of this repostory 

### ISSUE THREAD

**Issue by furkanedu** [taion/scroll-behavior#77]
Please give a clear explanation of the purpose of this repository, why it is created, what exactly it offers etc ? I wondered why this repo is used in react-redux-universal-hot-example and I have no idea since there is no explanation.

**Comment by taion** [comment]
It's in the README.

**Comment by faceyspacey** [comment]
he's not alone. this repo needs a full-on example. it's too abstract for the uninitiated. my 2 cents.

**Comment by taion** [comment]
Well, what are you trying to do? In general, as noted, you should probably be using react-router-scroll or Found Scroll, instead of using this library directly.

**Comment by faceyspacey** [comment]
I see that now (though I don't see any reference to Found Scroll). ...The fork of `react-router-scroll` for the latest React Router that uses `history.listen` actually is the closest thing to a general example. It's what I begun using yesterday as the basis for the scroll restoration implementation I'm working on for:

https://github.com/faceyspacey/pure-redux-router

For people arriving at this repo before `react-router-scroll` (or before having used it), I think a simple example, even if just a few lines in the main readme, would go a long way. This is a pretty damn good repo in how general it is. There's no need for people to reinvent the wheel with something like this having solved all the annoying browser deficiencies. 

...here's how I think it should look:

https://github.com/taion/scroll-behavior/pull/118

**Comment by taion** [comment]
https://github.com/taion/scroll-behavior/pull/119
