### ISSUE TITLE
"webkitCancelAnimationFrame" is not defined

### ISSUE THREAD

**Issue by ikhilko** [taion/scroll-behavior#79]
Scroll-behavior uses "dom-helpers@^2.4.0" as a dependency. 
Unfortunately requestAnimationFrame polyfill from this library checks only availability of `window.<vendor>RequestAnimationFrame`, and if found some implementation doesn't check availability of `window.<vendor>CancelRequestAnimationFrame`. And this cause an issue in some mobile browsers (e.g. Samsung S3) that have `requestAnimationFrame` but doesn't have `cancelAnimationFrame`.
Can we use another realisation of `requestAnimationFrame` polyfill? Or it will be better to fix it in [https://github.com/react-bootstrap/dom-helpers](dom-helpers)? Thanks

**Comment by taion** [comment]
File the issue upstream
